import { defineConfig } from "@michaelthielemann/kestrel/defineConfig";
import exampleMigration from "./migrations/2026-09-03-example.ts";

export default defineConfig({
  modules: [
    { use: "@michaelthielemann/kestrel-blobstore-filesystem", config: { root: "./data/blobs" } },
    { use: "@michaelthielemann/kestrel-replication-sqlite", config: { file: "./data/kestrel.db" } },
    { use: "@michaelthielemann/kestrel-persistence-sqlite", config: { file: "./data/kestrel.db" } },
    { use: "@michaelthielemann/kestrel-sanitize-svg", config: {} },
    { use: "@michaelthielemann/kestrel-media-default", config: { allowedTypes: ["image/*", "application/pdf"], deniedTypes: ["text/html", "application/xhtml+xml"], maxBytes: 5242880, locales: ["de", "en"], defaultLocale: "de", prefix: "media/" } },
    { use: "@michaelthielemann/kestrel-images-default", config: {} },
    {
      use: "@michaelthielemann/kestrel-authn-multi",
      config: {
        identifier: "username",
        minPasswordLength: 8,
        sessionTtlSeconds: 86400,
        bootstrap: { username: "admin", passwordHash: "scrypt$522f4ac87bfe4bcd100ba47a7d2aaec2$dbfc3f2d6cc38a76b21973d7c6f6d310a09506581c665f1f6601fd8fb3fa9bc3959689aea3e389f4d53eb8c7e70791ad4065e308763dd44609904134f0f5ee98", roles: ["admin"] },
      },
    },
    { use: "@michaelthielemann/kestrel-authz-roles", config: { roles: { admin: ["*"], editor: ["pages.*", "media.*", "images.read", "settings.read", "redirects.*"] }, anonymous: ["pages.read", "settings.read", "media.read"] } },
    {
      use: "@michaelthielemann/kestrel-content-default",
      config: {
        locales: ["de", "en"],
        defaultLocale: "de",
        types: {
          pages: {
            kind: "multi",
            fields: {
              slug: { type: "slug", required: true, unique: true, localized: true },
              title: { type: "text", required: true, localized: true },
              body: { type: "json", localized: true },
              status: { type: "enum", options: ["draft", "finished", "published"], required: true, localized: true },
              hero: { type: "ref", to: "media" },
              seo: { type: "json", localized: true },
            },
            completeWhen: { field: "status", equals: "published" },
          },
          redirects: { kind: "single", fields: { rules: { type: "json" } } },
          settings: { kind: "single", fields: { title: { type: "text", required: true, localized: true }, description: { type: "text", localized: true }, navigation: { type: "json", localized: true } } },
        },
      },
    },
    { use: "@michaelthielemann/kestrel-site-default", config: {} },
    { use: "@michaelthielemann/kestrel-references-default", config: { targets: { pages: { content: "pages" }, media: { collection: "media_items" } } } },
    { use: "@michaelthielemann/kestrel-links-default", config: { timeoutMs: 10000, concurrency: 4, recheckAfterSeconds: 21600 } },
    { use: "@michaelthielemann/kestrel-validate-jsonschema", config: { schemas: { "pages.body": "./schemas/blocks.json", "redirects.rules": "./schemas/redirects.rules.json", "settings.navigation": "./schemas/settings.navigation.json" } } },
    { use: "@michaelthielemann/kestrel-migrations-default", config: { migrations: [exampleMigration], mode: "apply" } },
    { use: "@michaelthielemann/kestrel-renderer-plain", config: { siteName: "Kestrel example" } },
    { use: "@michaelthielemann/kestrel-delivery-static", config: { types: { pages: {} }, prefix: "site/", media: { publicPath: "/media" }, llms: { full: true, headings: { pages: "Pages" } } } },
    { use: "@michaelthielemann/kestrel-redirects-default", config: { prefix: "site/" } },
    { use: "@michaelthielemann/kestrel-audit-persistence", config: {} },
    { use: "@michaelthielemann/kestrel-events-inmemory", config: {} },
    { use: "@michaelthielemann/kestrel-ratelimit-memory", config: { buckets: { login: { limit: 5, windowSeconds: 60 } } } },
  ],
  triggers: [
    { http: "POST /login", pipeline: "login" },
    { http: "POST /logout", pipeline: "logout" },
    { http: "GET /me", pipeline: "me" },
    { http: "POST /me/password", pipeline: "changePassword" },
    { http: "GET /users", pipeline: "listUsers" },
    { http: "POST /users", pipeline: "createUser" },
    { http: "GET /users/:id", pipeline: "getUser" },
    { http: "PUT /users/:id/password", pipeline: "setPassword" },
    { http: "DELETE /users/:id", pipeline: "deactivateUser" },
    { http: "POST /users/:id/activate", pipeline: "activateUser" },
    { http: "GET /admin/publish-status/pages/:id", pipeline: "pagePublishStatus" },
    { http: "POST /admin/publish-all/pages", pipeline: "publishAllPages" },
    { http: "GET /admin/references/broken", pipeline: "brokenReferences" },
    { http: "GET /admin/references/to/pages", pipeline: "pageReferrersMany" },
    { http: "GET /admin/references/to/media", pipeline: "mediaReferrersMany" },
    { http: "GET /admin/references/to/pages/:id", pipeline: "pageReferrers" },
    { http: "GET /admin/references/to/media/:id", pipeline: "mediaReferrers" },
    { http: "POST /admin/references/rebuild", pipeline: "rebuildReferences" },
    { cron: "30 2 * * *", pipeline: "scanReferences" },
    { http: "GET /admin/links/broken", pipeline: "brokenLinks" },
    { http: "POST /admin/links/rebuild", pipeline: "rebuildLinks" },
    { cron: "0 3 * * *", pipeline: "checkLinks" },
    { cron: "0 * * * *", pipeline: "cleanupSessions" },
    { cron: "*/5 * * * *", pipeline: "sweepRateLimits" },
    { http: "GET /settings", pipeline: "getSettings" },
    { http: "PUT /settings", pipeline: "setSettings" },
    { http: "GET /redirects", pipeline: "getRedirects" },
    { http: "PUT /redirects", pipeline: "setRedirects" },
    { http: "GET /redirects.json", pipeline: "renderRedirects" },
    { http: "GET /site/*path", pipeline: "resolvePage" },
    { http: "GET /pages", pipeline: "listPages" },
    { http: "GET /admin/pages", pipeline: "listAllPages" },
    { http: "GET /admin/pages/:id", pipeline: "readAnyPage" },
    { http: "GET /pages/:id", pipeline: "readPage" },
    { http: "POST /pages", pipeline: "createPage" },
    { http: "PATCH /pages/:id", pipeline: "updatePage" },
    { http: "DELETE /pages/:id", pipeline: "deletePage" },
    { http: "DELETE /pages/:id/translations/:locale", pipeline: "deletePageTranslation" },
    { http: "POST /media", pipeline: "uploadMedia" },
    { http: "GET /media/folders", pipeline: "listMediaFolders" },
    { http: "POST /media/folders", pipeline: "createMediaFolder" },
    { http: "PATCH /media/folders/*path", pipeline: "renameMediaFolder" },
    { http: "DELETE /media/folders/*path", pipeline: "deleteMediaFolder" },
    { http: "GET /media", pipeline: "listMedia" },
    { http: "GET /media/:id", pipeline: "getMedia" },
    { http: "GET /media/:id/file", pipeline: "downloadMedia" },
    { http: "GET /media/:id/variants/:file", pipeline: "serveImageVariant" },
    { http: "PATCH /media/:id", pipeline: "updateMedia" },
    { http: "POST /admin/media/export", pipeline: "exportMedia" },
    { http: "DELETE /media/:id", pipeline: "deleteMedia" },
    { http: "PUT /admin/images/sizes", pipeline: "registerImageSizes" },
    { http: "GET /admin/images/sizes", pipeline: "listImageSizes" },
    { http: "POST /admin/images/sync", pipeline: "syncImages" },
    { http: "POST /admin/images/prune", pipeline: "pruneImages" },
    { http: "GET /admin/images/status", pipeline: "imagesStatus" },
    { http: "GET /admin/migrations", pipeline: "listMigrations" },
    { http: "POST /admin/migrations/apply", pipeline: "applyMigrations" },
    { event: "media.uploaded", pipeline: "generateImageVariants" },
    { cron: "*/5 * * * *", pipeline: "resumeImages" },
    { cron: "* * * * *", pipeline: "replicate" },
    { http: "GET /admin/replication/status", pipeline: "replicationStatus" },
    { http: "GET /admin/replication/points", pipeline: "replicationPoints" },
    { http: "POST /admin/replication/snapshot", pipeline: "replicationSnapshot" },
    { http: "POST /admin/replication/restore", pipeline: "replicationRestore" },
    { event: "auth.loggedIn", pipeline: "auditAuth" },
    { event: "auth.loggedOut", pipeline: "auditAuth" },
  ],
  http: { port: 4000, host: "127.0.0.1", corsOrigin: "http://localhost:3000", inlineTypes: ["image/svg+xml"] },
});
