import { Effect } from 'effect'
import { ValidationFailed } from '@michaelthielemann/kestrel-contracts'

/** @public */
export interface LocaleConfig {
  readonly supported: readonly string[]
  readonly primary: string
}

function normalize(value?: string | string[] | null): string {
  const single = Array.isArray(value) ? value[0] : value
  return (single ?? '').trim().toLowerCase()
}

/**
 * Normalize a locale from a write body or a read query: trim + lowercase, default to `config.primary`
 * when absent, fail when explicitly given but not in `config.supported`. Shared decision behind both the
 * write and read paths' locale resolution, so a WHERE filter and the populate locale can never drift apart.
 */
export function resolveLocale(config: LocaleConfig, value?: string | string[] | null): Effect.Effect<string, ValidationFailed> {
  const normalized = normalize(value)
  if (!normalized) return Effect.succeed(config.primary)
  if (!config.supported.includes(normalized)) {
    return Effect.fail(new ValidationFailed({ issues: [{ path: ['locale'], message: `Unsupported locale: ${normalized}` }] }))
  }
  return Effect.succeed(normalized)
}

/** @public */
export interface ResolveUnitLocaleInput {
  kind: 'create' | 'update'
  translatable: boolean
  multiTranslation: boolean
  isSingletonWrite: boolean
  singletonLocale?: string
  hasLocaleKey: boolean
  locale?: string | string[] | null
  hasTranslationGroupKey: boolean
  /** Pre-generated by the shell (a core must not call `nanoid`/`Math.random`); used only when the
   *  decision actually needs a new translation-group id. */
  translationGroupCandidate: string
}

/** @public */
export interface ResolveUnitLocaleOutput {
  /** `undefined` — leave `unit.values.locale` untouched. */
  locale?: string
  translationGroup?: string
}

/**
 * The per-write-unit locale/translation-group decision `resolveLocaleStep` applies. A non-translatable
 * collection, or an update that doesn't touch `locale`, is a no-op (both fields left `undefined`).
 * @public
 */
export function resolveUnitLocale(config: LocaleConfig, input: ResolveUnitLocaleInput): Effect.Effect<ResolveUnitLocaleOutput, ValidationFailed> {
  if (!input.translatable) return Effect.succeed({})
  if (input.kind === 'create') {
    return resolveLocale(config, input.locale).pipe(Effect.map((locale) => ({
      locale,
      translationGroup: input.multiTranslation && !input.hasTranslationGroupKey ? input.translationGroupCandidate : undefined,
    })))
  }
  if (input.isSingletonWrite) return Effect.succeed({ locale: input.singletonLocale })
  if (!input.hasLocaleKey) return Effect.succeed({})
  return resolveLocale(config, input.locale).pipe(Effect.map((locale) => ({ locale })))
}
